### ISSUE TITLE
My OBS cannot connect to the janus server that I built 

### ISSUE THREAD

**Issue by LuckeX** [CoSMoSoftware/OBS-studio-webrtc#64] opened 2019-01-09 08:53 UTC
The detail like this 
"
16:45:44.451: janus_stream_defaults
16:45:44.451: janus_stream_create
16:45:44.454: Output 'simple_stream': Tried to set a delay value on a non-encoded output
16:45:44.454: janus_stream_start
16:45:44.458: connecting to [url:wss://10.239.10.92,room:1234,username:,password:]
16:45:45.550: onDisconnected
16:45:45.551: ==== Streaming Stop ========
"My janus server is running successfully, but my OBS-studio-webrtc cannot connect to it , so what should I do to solve this problem?
Thank you very much!

**Comment by agouaillard-cosmo** [comment] 2019-01-14 08:55
does it run successfully against the default hosted video room demo?
https://janus.conf.meetecho.com/videoroomtest.html

**Comment by Akhawais** [comment] 2019-02-23 23:32
Hi, I'm also having this issue. My log is showing the exact same (except the url of course).

The video room demo of the same Janus gateway is working very well.

Thanks!

**Comment by agouaillard-cosmo** [comment] 2019-02-26 16:26
Hi @Akhawais

To be able to narrow the scope, i.e. to know wether the problem comes from OBS and janus on one hand, or your version of janus, I would need you to make a little test. Can you try to connect to the hosted janus server, by providing the following ws server URL to OBS and see if you can connect. 
ws://janus.conf.meetecho.com:8188

You can tell if you were successful by connecting to the web app, and check that the stream sent by OBS appears on the web page.

**Comment by Akhawais** [comment] 2019-02-26 16:37
Hi @agouaillard-cosmo

Actually a few hours ago I found the solution. Apologies for not updating my comment until now.

Janus does not come with the websocket transport plugin out of the box. It must be configured in order to use ws/wss. I thought that since it’s a WebRTC gateway it would have support preinstalled. 

Many thanks for your quick reply and for your repo. It is allowing me to uncover new possibilities. I have some issues with choosing bandwidth but I am 99% sure it’s a problem with Janus so will check with them.

~ Dylan

**Comment by agouaillard-cosmo** [comment] 2019-02-27 20:50
good. I assume the problem is solved for @LuckeX and close this issue. If it s still a problem, go ahead and open a new issue.

**Closed by agouaillard-cosmo** 2019-02-27 20:50 UTC
Labels: bug
