### ISSUE TITLE
EBS: Start menu link triggers error message

### ISSUE THREAD

**Issue by chadfurman** [CoSMoSoftware/OBS-studio-webrtc#106] opened 2019-07-09 04:15 UTC
Could relate to #82 

Installing EBS and then accessing it in the start menu asks to find the exe.  If the EXE is located manually via that dialog, then the application fails to load with "missing locale"

**Comment by agouaillard-cosmo** [comment] 2019-07-11 03:51
The link part is a duplicate of #82. I m seeing this bug around to check if solving #82 would solve the locale problem as well.

**Comment by agouaillard-cosmo** [comment] 2019-07-11 04:57
done, waiting QA. Automated build passed.

**Comment by agouaillard-cosmo** [comment] 2019-07-25 22:10
fixed: removed from now. Menu still in place with the uninstall shortcut.

**Closed by agouaillard-cosmo** 2019-07-25 22:10 UTC
Labels: bug, windows
