### ISSUE TITLE
NDI audio sizzle

### ISSUE THREAD

**Issue by colinbouvry** [CoSMoSoftware/OBS-studio-webrtc#292] opened 2021-01-27 19:42 UTC
Hello,

When I exchange NDI streams from OBS 26.1.1 and obs-ndi 4.9.1  I get a crackle sound under OBS-Studio 26 WebRTC m86- Beta 1

This does not happen with the standard obs studio version and ndi plugin.

All under windows 10 !

Any idea ?

**Comment by agouaillard-cosmo** [comment] 2021-01-29 09:49
Hi colin,
thanks for the report.
Which version did you use? Would you mind to try to replicate with latest m88v26.1.2 ?

**Comment by findingpixels** [comment] 2021-02-09 18:21
I can also confirm audio issue with 26.1.2 when using NDI audio. I got around it by using NDI Tools Virtual Camera and picking up that audio. Hacky for sure, but worked for the moment.

**Comment by fiveohfiveoh** [comment] 2021-02-12 23:47
Can also confirm this is happening with 26.1.2 when using NDI audio - on macOS Catalina 10.15.6. NDI Audio is fine with vanilla OBS on the same system.

**Comment by agouaillard-cosmo** [comment] 2021-02-12 23:50
Happy new year of the Ox all.
We are experiencing some audio quality problem with rtmp ingest. Just to make sure this is a separate problem, could you kindly check if the problem still exists when using NDI audio input with millicast webrtc ingest?
thanks in advance.

**Comment by agouaillard-cosmo** [comment] 2021-02-13 00:04
Thanks for taking the time to confirm the problem. I have currently an engineer full time on the audio issue, I will make sure he tackles this at the same time. We might delay a little bit our CNY release to bring that fix in.

**Comment by fiveohfiveoh** [comment] 2021-02-13 00:08
Awesome, thank you!

**Comment by agouaillard-cosmo** [comment] 2021-02-16 06:15
@ludocosmo Can you kindly try to reproduce it, and narrow down OS, transport, ....

**Comment by fileintegrity** [comment] 2021-03-19 21:42
Just tried this on 
obs-webrtc-x64-26.1.2-m90
obs-webrtc-x64-26.1.2-m88
and the standard (non webrtc) OBS:
OBS-Studio-26.1.1-Full-Installer-x64

**Comment by matthewclickbid** [comment] 2021-03-19 22:04
Similar experience with OSX m90 using production output via NDI FROM Adobe Preimere using Millicast WebRTC. Did not test Millicast RTMP.

**Comment by deadpixel-cell** [comment] 2021-03-31 23:09
Got the same issue regarding audio crackling. Tried with VMIX, NDI Monitor and standard OBS with no issue. as fiveohfiveoh said it seems to be coming out from the OBS-WebRTC itself.

Spec:
using: OBS-Studio 26.1.2 WebRTC m90
NDI Video source: 1080p50 but also happen in another format like 1080i50
NDI audio: I have tried 2ch audio embed NDI's or 8 Tracks of NDI embed
OS: Windows 10 Pro Running on a VM with VB-Cable install for loopback listen on Remote software like anydesk
OS Audio interface sample rate: 48kHz 24bit (made no difference on other format
Cpu usage while running: 8%

Milli encoding mode: h264 or vp9, 4mbit, 48khz stereo. 1080p 25fps output

**Comment by agouaillard-cosmo** [comment] 2021-04-07 07:27
This is a ticket that will require lots of work and specific hardware.
We have not started it yet, and there is only one week left in this sprint.
The websocket redesign and fixes takes precedence.
Moving this ticket to next sprint.

**Comment by fiveohfiveoh** [comment] 2021-04-18 19:33
After some more investiagtion, I have found that this is only happening in one audio channel - the right one. If I go to Advanced Audio Properties and select 'Mono' and drag the balance all the way to L, I don't get any audio distortion / crackle. 

Here's a screengrab of the settings that do not result in the audio crackle for me: 
![Screenshot 2021-04-18 at 20 30 26](https://user-images.githubusercontent.com/59825900/115158241-1e0a0600-a085-11eb-806f-c3136f8e1c56.png)

There are a few issues in the NDI Palakis repo referring to a similar issue, but with no apparent solution:
https://github.com/Palakis/obs-ndi/issues/548
https://github.com/Palakis/obs-ndi/issues/574
https://github.com/Palakis/obs-ndi/issues/24

**Comment by nixinator** [comment] 2021-04-25 03:04
we have been playing around with two linux system, arch and NixOS with ndi-obs Seems that the latest obs-ndi of the tip of master has the problem. We reverted both the systems to the obs-ndi 4.9.1 tagged release and everything worked well.  22c7f7c https://github.com/Palakis/obs-ndi/releases/tag/4.9.1  . I hope this helps.

**Comment by ludocosmo** [comment] 2021-04-28 10:44
Revert to obs-ndi 4.9.1 to solve the problem.

**Comment by nigelgourley** [comment] 2021-05-16 17:45
> Revert to obs-ndi 4.9.1 to solve the problem.

Revert to 4.9.1 that seems to be later than the latest win 10 version 4.9.0? We have exactly the same issue and found it only happens only on the Right channel also.

**Comment by matthewclickbid** [comment] 2021-05-16 18:19
So the solution is to pan to the left channel in OBS? Is there a way to send the left channel to both l/r output once you've done that?

**Comment by nigelgourley** [comment] 2021-05-16 18:22
I think if you pan left then that's taking all the Left channeld from the NDI source and sending that to both outputs in a stereo config

**Closed** 2021-05-20 06:25 UTC
Labels: bug

**Comment by imeiul** [comment] 2022-11-08 00:02
I had the same problem.
I'm using this fork that didn't have the problem.
https://github.com/dev47apps/obs-ndi
