### ISSUE TITLE
JNS: Unable to connect from OBS to local install of Janus.

### ISSUE THREAD

**Issue by kinsago** [CoSMoSoftware/OBS-studio-webrtc#219] opened 2020-06-01 11:03 UTC
Hi all,

Hoping for some assistance here please as I've explored every option I can think of.

I have Janus installed and have configured secure websockets.  Janus start up log indicates that Secure Web Sockets is running on port 8989.

I've amended the videoroom demo to use secure websockets so I'm happy that it's working ok, at least through the website.  Screenshot showing web console output is below.

![image](https://user-images.githubusercontent.com/8029064/83402063-fa52b880-a3fd-11ea-8ce4-6b77d0a48640.png)

When I try to use the same details in OBS I get the message "An unexpected error occurred when trying to connect to the server".  The log shows:

```
11:50:27.415: Output 'simple_stream': Tried to set a delay value on a non-encoded output
11:50:27.415: janus_stream_start
11:50:27.418: connecting to [url:wss://*****************.com,room:1234,username:,password:]
11:50:27.549: onDisconnected
11:50:27.550: ==== Streaming Stop ================================================
```

I've tried pointing OBS at the Janus demos online (wss://janus.conf.meetecho.com/ws) and it works fine.  I just can't seem to work out what I'm missing or where to go next.

I'm using a certificate provided by letsencrypt if that makes a difference?  Chrome shows the certificate as valid so I don't think it's authentication either or because I'm trying to self-certify.

Any assistance would be greatly appreciated!!

Philip

**Comment by agouaillard-cosmo** [comment] 2020-06-01 11:53
1. you can disregard this line in the log "11:50:27.415: Output 'simple_stream': Tried to set a delay value on a non-encoded output"
2. if it works against the reference Janus instance, you re pretty much on your own.
3. To put you in the right direction, you're having a WS connection problem, so on OBS side, this is dealt with in the web socket plugin. You should point your debugger to the WebsocketClient.cpp and januswebsocketclient.cpp code, put a break point on the websocket callbacks (ike onDisconnected) and check what is happening there.

**Comment by kinsago** [comment] 2020-06-02 16:18
Thanks, I spun up a new server and it's working as expected on the second server.  I'm going to try comparing the two configurations now and see if I can see any differences that could cause this.  If I can resolve it I'll report back for future reference.

**Comment by agouaillard-cosmo** [comment] 2020-06-04 11:23
Thanks. I'm going to close this bug, but you should still be able to comment when you find the root cause.

**Closed by agouaillard-cosmo** 2020-06-04 11:23 UTC
Labels: 79, help wanted
